### ISSUE TITLE
Connection::initialize might be the wrong interface

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/lsp-server#13]
It turns out that `ServerCapabilities` may need to be modified based on `ClientCapabilities` before being sent out but that cannot be done with the current library (we can only access `ClientCapabilities` after constructing server capabilities. In addition since LSP 3.15 `InitializeResult` can have a `serverInfo` field to pass back to the client which is also not supported by this interface.

Context: https://github.com/rust-analyzer/rust-analyzer/issues/4130

**Comment by matklad** [comment]
Great observation!
