### ISSUE TITLE
Need additional info on goto_def example and server interfacing.

### ISSUE THREAD

**Issue by Hyperion101010** [rust-analyzer/lsp-server#16]
HI there,
I am working on a vscode extension + Solidity server in rust for providing support for Solidity language in hyperledger. 
I was trying the goto_def example and I hit some hurdles while doing so.
1. There is no correct way defined to interface the client side with server. I tried running the goto_def example but unfortunately it sometimes appears and sometimes not in the output of vscode console. So i would like to have some clarification on that.
A screenshot for understanding:
![servercli](https://user-images.githubusercontent.com/32175777/85123620-34b5b580-b246-11ea-8465-62e03f1842ed.png)

The repo: https://github.com/Hyperion101010/sls/tree/p1_work

Also as there is very little resource available on the server part of the vscode extension development. I would appreciate any useful docs/blogs if you have come across for server development in other language like rust, python except ts and nodejs.

**Comment by matklad** [comment]
Yeah, sadly the lsp-server crate is pretty scarce in terms of documentation. It works well enough for rust-analyzer, but it explicitly is not aiming to be a good general purpose library at the moment.

The best way forward would be:

* to look at how rust-analyzer is doing things
* do everything yourself
* use tower-lsp crate
