### ISSUE TITLE
There should be an empty success function

### ISSUE THREAD

**Issue by jD91mZM2** [rust-analyzer/lsp-server#2]
If I'm reading for example https://microsoft.github.io/language-server-protocol/specification#textDocument_definition correctly, it must be able to return `null`, which would correspond to having `None` in the place of the Response's `result` field. I realize that the fields are public and thus it's not important, but having an `new_none` constructor similar to `new_ok` would be great :)

**Comment by matklad** [comment]
That should be `Response::new_ok(id, ())`.

**Comment by jD91mZM2** [comment]
Oh, right! Sorry :)
