### ISSUE TITLE
panic on missing `version` field in `textDocument/didSave`

### ISSUE THREAD

**Issue by poliorcetics** [rust-analyzer/lsp-server#23]
## Current behaviour

When a field is missing in a notification, `lsp-server` panics:

```
Invalid notification
Method: textDocument/didSave
 error: missing field `version`
```

Position:

```
lsp-server-0.5.0/src/msg.rs:192:17
```

## Expected behaviour

While I would understand `lsp-server` returning an error, panicking seems like a bug.

## Additional informations

- neovim/neovim#13344
- rust-analyzer/rust-analyzer#6603

**Comment by poliorcetics** [comment]
Lines: https://github.com/rust-analyzer/lsp-server/blob/master/src/msg.rs#L189-L198

Is it required for this to panic or could it return either the original notification in `Result::Err` or a new composite error enum ?

**Comment by poliorcetics** [comment]
As said in microsoft/language-server-protocol#1147, this is an error on the spec which introduced a breaking change, so I'll make a PR on `lsp-types` instead of here.

**Comment by JoshMcguigan** [comment]
I've run into a similar issue with `textDocument/didOpen`.

```
got notification: Notification {
    method: "textDocument/didOpen",
    params: Object({
        "textDocument": Object({
            "languageId": String(
                "gdb",
            ),
            "text": String(
                "define heyo\n\techo heyo\nend\n\nheyo\n",
            ),
            "uri": String(
                "file:///home/josh/workspace/test.gdb",
            ),
            "version": Number(
                1,
            ),
        }),
    }),
}
thread 'main' panicked at 'Invalid notification
Method: textDocument/didOpen
 error: invalid type: map, expected a tuple of size 2', /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.1/src/msg.rs:213:17
```

Currently the extract method returns `Result<P, Notification>`, where the `Err` case is used to denote the method not matching, and a panic happening if the method matches but deserialization fails. 

Perhaps the extract method could instead be something like:

```
enum ExtractResult<P, N> {
    Ok(P),
    MethodNotMatch(N),
    DeserializationError(serde_json::Error),
}

pub fn extract<P: DeserializeOwned>(self, method: &str) -> ExtractResult<P, Notification> {..}
```

Any callers of this method could  of course still `panic` if that is how they want to handle that situation, but it allows recovering from this situation. I imagine this change could require some minor changes to rust-analyzer? 

I'd be happy to work on this if a PR would be accepted? 

Edit to clarify that in my case the specific cause of the type mismatch (and thus the panic) was an error in my usage of the `lsp-server` library and not a problem with `lsp-types`, but I still think it might be nice to avoid a panic here.
