### ISSUE TITLE
Async version of the server

### ISSUE THREAD

**Issue by bartlomieju** [rust-analyzer/lsp-server#26]
Thanks for creating this project! It's been a tremendous help when implementing `deno lsp` (https://github.com/denoland/deno/tree/master/cli/lsp). 

However due to synchronous nature of the server we've hit a few problems that required us to "asyncify" the server. We did it by spawning a separate thread that "pumps" messages received from the client. This solution works for now, but requires additional infrastructure to cooperate with Tokio. 

So here's my question; is there an interest from `rust-analyzer` team in having an async version of the server? The codebase is relatively small and porting it to use Tokio should be rather a straightforward task. I'll be also happy to fork the project and provide a separate crate once #25 is answered.

CC @matklad

**Comment by bartlomieju** [comment]
Actually we'll try out `tower-lsp` first, seems it might cover our need :) Closing for now

**Comment by matklad** [comment]
Yup, it's design choice that this lib is synchronous, tower-lsp would be your best bet!
