### ISSUE TITLE
Invalid method name leads to a panic

### ISSUE THREAD

**Issue by puuuuh** [rust-analyzer/lsp-server#37]
[DEBUG][2021-10-08 06:46:46] .../vim/lsp/rpc.lua:395	"rpc.send"	{  id = 3,  jsonrpc = "2.0",  method = 0,  params = "textDocument/formatting"}
[ERROR][2021-10-08 06:46:46] .../vim/lsp/rpc.lua:459	"rpc"	"rust-analyzer"	"stderr"	"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/puh/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.2/src/req_queue.rs:60:34\nstack backtrace:\n"

**Comment by bjorn3** [comment]
The problem seems to be calling `Outgoing::complete` for a request that hasn't been registered first: https://github.com/rust-analyzer/lsp-server/blob/d2737a9250da610fcb0ba34930606c39b85e5469/src/req_queue.rs#L59-L61
