### ISSUE TITLE
Recommended testing strategy

### ISSUE THREAD

**Issue by lpil** [rust-analyzer/lsp-server#40]
Hello!

Thanks for this library, it looks very handy :)

Is there a recommended testing strategy for when using this library? Would you test it via the `Connection` or might you focus on the functions that the `Connection` handling code dispatches individual messages to?

Thanks,
Louis

**Comment by matklad** [comment]
See slow_tests in rust-analyzer for an example of how is this used: 

https://github.com/rust-analyzer/rust-analyzer/blob/1d5df5ea941ec814649ebe5e16c8c324fdc9cebd/crates/rust-analyzer/tests/slow-tests/main.rs#L42-L75

This worked OK for us so far! At this level of abstraction, you can also test by just spinning a binary and communicating via `stdio`. Using `LSP` layer for tests I think should work great for small-medium size language servers. For something bigger like RA, I would probably advice to concentrate tests on a layer below that. For example, rust-analyzer has `ide` crate which defines a library API, and the bulk of tests are run at that layer: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/lib.rs

**Comment by lpil** [comment]
That's super useful, thank you very much!
